/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2010-04-25, 19:40:25
 */

package piotrrr.thesis.gui;

import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

import piotrrr.thesis.bots.BotsConfig;
import piotrrr.thesis.bots.botbase.BotBase;
import piotrrr.thesis.bots.referencebot.ReferenceBot;
import piotrrr.thesis.bots.smartbot.SmartBot;
import piotrrr.thesis.bots.wpmapbot.MapBotBase;
import piotrrr.thesis.common.CommFun;
import piotrrr.thesis.common.GameObject;
import piotrrr.thesis.common.jobs.GlobalKillsStatsJob;
import piotrrr.thesis.common.jobs.DebugStepJob;
import piotrrr.thesis.common.jobs.HitsReporter;
import piotrrr.thesis.common.stats.BotStatistic;
import piotrrr.thesis.common.stats.StatsChartsFactory;
import soc.qase.tools.vecmath.Vector3f;

/**
 *
 * @author piotrrr
 */
public class MainFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        setUpdater();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        panelRunBots = new javax.swing.JPanel();
        nrBotsField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        connectOthersButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        connectedBotsList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        selectedBotInfoTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        disconnectSelectedButton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        connectDebugedButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nrOfSmartBotsTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        connectSmartBotsjButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        messagesScrollPane1 = new javax.swing.JScrollPane();
        messages = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        allEntsRadioButton1 = new javax.swing.JRadioButton();
        visibleWaypointsRadioButton2 = new javax.swing.JRadioButton();
        navPlanRadioButton = new javax.swing.JRadioButton();
        visibleEntsRadioButton2 = new javax.swing.JRadioButton();
        pickupFailuresRadioButton1 = new javax.swing.JRadioButton();
        edgeFailuresRadioButton = new javax.swing.JRadioButton();
        enemyInfoRadioButton1 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        fullInfoScrollPane3 = new javax.swing.JScrollPane();
        fullInfo = new javax.swing.JTextArea();
        goToButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        distanceLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        reqListScrollPane2 = new javax.swing.JScrollPane();
        reqList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        pauseToggleButton = new javax.swing.JToggleButton();
        pauseAnotherBotsToggle = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        sendCommandToDBGButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sendCommandToAnothersButton = new javax.swing.JButton();
        stepSizeTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stepButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        botStateInfoTextArea1 = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        killsPanel14 = new javax.swing.JPanel();
        killsByTypejPanel14 = new javax.swing.JPanel();
        deathsByTypejPanel14 = new javax.swing.JPanel();
        weaponsjPanel14 = new javax.swing.JPanel();
        killsePerDeathjPanel14 = new javax.swing.JPanel();
        whoKillsWhomjPanel14 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bot Debugging");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelRunBots.setBorder(javax.swing.BorderFactory.createTitledBorder("Connect Reference bots"));

        nrBotsField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        nrBotsField.setText("2");

        jLabel1.setText("Connect");

        jLabel2.setText("ReferenceBots");

        connectOthersButton.setText("Connect them!");
        connectOthersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectOthersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRunBotsLayout = new javax.swing.GroupLayout(panelRunBots);
        panelRunBots.setLayout(panelRunBotsLayout);
        panelRunBotsLayout.setHorizontalGroup(
            panelRunBotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRunBotsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nrBotsField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(connectOthersButton)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        panelRunBotsLayout.setVerticalGroup(
            panelRunBotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRunBotsLayout.createSequentialGroup()
                .addGroup(panelRunBotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrBotsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(connectOthersButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Connected bots"));

        connectedBotsList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                connectedBotsList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(connectedBotsList1);

        selectedBotInfoTextArea1.setColumns(20);
        selectedBotInfoTextArea1.setRows(5);
        jScrollPane3.setViewportView(selectedBotInfoTextArea1);

        jLabel4.setText("Selected bot info:");

        disconnectSelectedButton1.setText("Disconnect selected bot");
        disconnectSelectedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectSelectedButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(disconnectSelectedButton1))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(disconnectSelectedButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Connect debugged bot"));

        connectDebugedButton.setText("Connect debuged bot");
        connectDebugedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectDebugedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(connectDebugedButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(connectDebugedButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Connect SmartBots"));

        jLabel5.setText("Connect");

        nrOfSmartBotsTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        nrOfSmartBotsTextField2.setText("1");
        nrOfSmartBotsTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrOfSmartBotsTextField2ActionPerformed(evt);
            }
        });

        jLabel8.setText("SmartBots");

        connectSmartBotsjButton1.setText("Connect them!");
        connectSmartBotsjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectSmartBotsjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nrOfSmartBotsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(connectSmartBotsjButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nrOfSmartBotsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(connectSmartBotsjButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(290, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelRunBots, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(290, 290, 290))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRunBots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Connect bots", jPanel7);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Messages"));

        messages.setColumns(20);
        messages.setRows(5);
        messagesScrollPane1.setViewportView(messages);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagesScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(messagesScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bot world info"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Display info options"));

        infoButtonGroup.add(allEntsRadioButton1);
        allEntsRadioButton1.setSelected(true);
        allEntsRadioButton1.setText("all entities in the WorldKB");
        allEntsRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allEntsRadioButton1ActionPerformed(evt);
            }
        });

        infoButtonGroup.add(visibleWaypointsRadioButton2);
        visibleWaypointsRadioButton2.setText("visible waypoints");
        visibleWaypointsRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleWaypointsRadioButton2ActionPerformed(evt);
            }
        });

        infoButtonGroup.add(navPlanRadioButton);
        navPlanRadioButton.setText("navigation plan details");
        navPlanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navPlanRadioButtonActionPerformed(evt);
            }
        });

        infoButtonGroup.add(visibleEntsRadioButton2);
        visibleEntsRadioButton2.setText("visible entities");
        visibleEntsRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleEntsRadioButton2ActionPerformed(evt);
            }
        });

        infoButtonGroup.add(pickupFailuresRadioButton1);
        pickupFailuresRadioButton1.setText("pickup failures");
        pickupFailuresRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupFailuresRadioButton1ActionPerformed(evt);
            }
        });

        infoButtonGroup.add(edgeFailuresRadioButton);
        edgeFailuresRadioButton.setText("edge failures");
        edgeFailuresRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edgeFailuresRadioButtonActionPerformed(evt);
            }
        });

        infoButtonGroup.add(enemyInfoRadioButton1);
        enemyInfoRadioButton1.setText("enemy information");
        enemyInfoRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enemyInfoRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visibleWaypointsRadioButton2)
                    .addComponent(pickupFailuresRadioButton1)
                    .addComponent(allEntsRadioButton1)
                    .addComponent(visibleEntsRadioButton2)
                    .addComponent(navPlanRadioButton)
                    .addComponent(edgeFailuresRadioButton)
                    .addComponent(enemyInfoRadioButton1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allEntsRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visibleEntsRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visibleWaypointsRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pickupFailuresRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navPlanRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edgeFailuresRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enemyInfoRadioButton1)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Full information on selected item"));

        fullInfo.setColumns(20);
        fullInfo.setRows(5);
        fullInfoScrollPane3.setViewportView(fullInfo);

        goToButton.setText("Go to this position");
        goToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Distance from the bot:");

        distanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        distanceLabel.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fullInfoScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(distanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(goToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(distanceLabel)
                    .addComponent(goToButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullInfoScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Info items list"));

        reqList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reqList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                reqListValueChanged(evt);
            }
        });
        reqListScrollPane2.setViewportView(reqList);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reqListScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(reqListScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bot control"));

        pauseToggleButton.setText("Pause dbg bot");
        pauseToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseToggleButtonActionPerformed(evt);
            }
        });

        pauseAnotherBotsToggle.setText("Pause other bots");
        pauseAnotherBotsToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseAnotherBotsToggleActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("disc");

        sendCommandToDBGButton.setText("<html><center>send cmd <br> to dbg");
        sendCommandToDBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCommandToDBGButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Command: ");

        sendCommandToAnothersButton.setText("<html><center>send cmd <br> to others");
        sendCommandToAnothersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCommandToAnothersButtonActionPerformed(evt);
            }
        });

        stepSizeTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stepSizeTextField2.setText("10");

        jLabel7.setText("Step size:");

        stepButton1.setText("step");
        stepButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pauseToggleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pauseAnotherBotsToggle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(sendCommandToAnothersButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stepSizeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stepButton1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendCommandToDBGButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pauseToggleButton)
                    .addComponent(pauseAnotherBotsToggle))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sendCommandToAnothersButton)
                            .addComponent(sendCommandToDBGButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stepSizeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepButton1))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Debugged bot state info"));

        botStateInfoTextArea1.setColumns(20);
        botStateInfoTextArea1.setRows(5);
        jScrollPane1.setViewportView(botStateInfoTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Info & Control", jPanel6);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        killsPanel14.setLayout(new java.awt.GridLayout(1, 1, 5, 5));
        jTabbedPane2.addTab("kills by bot", killsPanel14);

        killsByTypejPanel14.setLayout(new java.awt.GridLayout());
        jTabbedPane2.addTab("kills by bot type", killsByTypejPanel14);

        deathsByTypejPanel14.setLayout(new java.awt.GridLayout());
        jTabbedPane2.addTab("deaths by bot type", deathsByTypejPanel14);

        weaponsjPanel14.setLayout(new java.awt.GridLayout());
        jTabbedPane2.addTab("weapons by bot", weaponsjPanel14);

        killsePerDeathjPanel14.setLayout(new java.awt.GridLayout());
        jTabbedPane2.addTab("kills per death", killsePerDeathjPanel14);

        whoKillsWhomjPanel14.setLayout(new java.awt.GridLayout());
        jTabbedPane2.addTab("who kills whom", whoKillsWhomjPanel14);

        jButton1.setText("Save current statistics");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Load statistics");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(refreshButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Statistics", jPanel13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectDebugedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectDebugedButtonActionPerformed
    	if (dbgBot != null) return;
    	SmartBot bot = new SmartBot("SmartBot-dbg", BotsConfig.skinName);
    	bot.addBotJob(new HitsReporter(bot));
		bot.connect(BotsConfig.serverIP, BotsConfig.serverPort);
		stepJob = new DebugStepJob(bot, this);
		bot.addBotJob(stepJob);
		bot.addBotJob(new GlobalKillsStatsJob(bot));
		dbgBot = bot;
                stats = BotStatistic.createNewInstance();
    }//GEN-LAST:event_connectDebugedButtonActionPerformed

    private void connectOthersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectOthersButtonActionPerformed
    	int num = Integer.parseInt(nrBotsField.getText());
    	for (int i=0; i<num; i++) {
    		ReferenceBot bot = new ReferenceBot("ReferenceBot-"+i, BotsConfig.skinName);
    		bot.dtalk.active = false;
    		bot.addBotJob(new HitsReporter(bot));
    		bot.connect(BotsConfig.serverIP, BotsConfig.serverPort);	
    		bots.add(bot);
    	}
    }//GEN-LAST:event_connectOthersButtonActionPerformed

    private void pauseToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseToggleButtonActionPerformed
       dbgBot.botPaused = pauseToggleButton.isSelected();
    }//GEN-LAST:event_pauseToggleButtonActionPerformed

    private void reqListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_reqListValueChanged
        int ind = reqList.getSelectedIndex();
        if (ind < 0 || ind > requiredList.size()) return;
        fullInfo.setText(requiredList.get(ind).toDetailedString());
        Vector3f lookAt = new Vector3f(requiredList.get(ind).getObjectPosition());
        dbgBot.setPauseLookAtPosition(lookAt);
        distanceLabel.setText(""+CommFun.getDistanceBetweenPositions(dbgBot.getBotPosition(), requiredList.get(ind).getObjectPosition()));
    }//GEN-LAST:event_reqListValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    	updater.stop = true;
        if (dbgBot != null) dbgBot.disconnect();
        for (MapBotBase b : bots) b.disconnect();
        bots.clear();
    }//GEN-LAST:event_formWindowClosing

    private void pauseAnotherBotsToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseAnotherBotsToggleActionPerformed
       for (MapBotBase b : bots) {
           b.botPaused = pauseAnotherBotsToggle.isSelected();
       }
    }//GEN-LAST:event_pauseAnotherBotsToggleActionPerformed

    private void sendCommandToDBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendCommandToDBGButtonActionPerformed
        String cmd = jTextField1.getText();
        dbgBot.handleCommand(cmd);
    }//GEN-LAST:event_sendCommandToDBGButtonActionPerformed

    private void sendCommandToAnothersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendCommandToAnothersButtonActionPerformed
    	String cmd = jTextField1.getText();
    	for (MapBotBase b : bots) b.handleCommand(cmd);
    }//GEN-LAST:event_sendCommandToAnothersButtonActionPerformed

    private void allEntsRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allEntsRadioButton1ActionPerformed
      Vector<GameObject> v = new Vector<GameObject>();
      //FIXMe:
      v.addAll(dbgBot.kb.getAllItems());
//      v.addAll(dbgBot.kb.getAllPickableEntities());
      setReqList(v);
    }//GEN-LAST:event_allEntsRadioButton1ActionPerformed

    private void visibleWaypointsRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleWaypointsRadioButton2ActionPerformed
    	 Vector<GameObject> v = new Vector<GameObject>();
         v.addAll(dbgBot.kb.getAllVisibleWaypoints());
         setReqList(v);
    }//GEN-LAST:event_visibleWaypointsRadioButton2ActionPerformed

    private void stepButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButton1ActionPerformed
       int steps = Integer.parseInt(stepSizeTextField2.getText());
       stepJob.pauseIn(steps);
    }//GEN-LAST:event_stepButton1ActionPerformed

    private void navPlanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navPlanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navPlanRadioButtonActionPerformed

    private void visibleEntsRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleEntsRadioButton2ActionPerformed
    	 Vector<GameObject> v = new Vector<GameObject>();
         v.addAll(dbgBot.kb.getAllVisibleEntities());
         setReqList(v);
    }//GEN-LAST:event_visibleEntsRadioButton2ActionPerformed

    private void pickupFailuresRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupFailuresRadioButton1ActionPerformed
    	Vector<GameObject> v = new Vector<GameObject>();
        v.addAll(dbgBot.kb.getAllEntsWithPickupFailure());
        setReqList(v);
    }//GEN-LAST:event_pickupFailuresRadioButton1ActionPerformed

    private void edgeFailuresRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edgeFailuresRadioButtonActionPerformed
//    	Vector<GameObject> v = new Vector<GameObject>();
//        v.addAll(dbgBot.kb.getAllEdgeFailures());
//        setReqList(v);
    }//GEN-LAST:event_edgeFailuresRadioButtonActionPerformed

    private void goToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToButtonActionPerformed
    	if (reqList.getSelectedIndex() == -1) return;
    	Vector3f dst = requiredList.elementAt(reqList.getSelectedIndex()).getObjectPosition();
       dbgBot.goToPositionWithNoClipCheating(dst);
    }//GEN-LAST:event_goToButtonActionPerformed

    private void enemyInfoRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enemyInfoRadioButton1ActionPerformed
    	Vector<GameObject> v = new Vector<GameObject>();
        v.addAll(dbgBot.kb.getAllEnemyInformation());
        setReqList(v);
    }//GEN-LAST:event_enemyInfoRadioButton1ActionPerformed

    private void connectSmartBotsjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectSmartBotsjButton1ActionPerformed
    	int num = Integer.parseInt(nrOfSmartBotsTextField2.getText());
    	for (int i=0; i<num; i++) {
    		SmartBot bot = new SmartBot("SmartBot-"+i, BotsConfig.skinName);
    		bot.dtalk.active = false;
    		bot.addBotJob(new HitsReporter(bot));
    		bot.connect(BotsConfig.serverIP, BotsConfig.serverPort);	
    		bots.add(bot);
    	}
    }//GEN-LAST:event_connectSmartBotsjButton1ActionPerformed

    private void connectedBotsList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_connectedBotsList1ValueChanged
    	int ind = connectedBotsList1.getSelectedIndex();
    	BotBase bot = getBotFromList(ind);
    	if (bot == null) return;
    	if (bot.getFrameNumber() < 2) return;
        selectedBotInfoTextArea1.setText(bot.toDetailedString());
    }//GEN-LAST:event_connectedBotsList1ValueChanged

    private void disconnectSelectedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectSelectedButton1ActionPerformed
    	int ind = connectedBotsList1.getSelectedIndex();
    	BotBase bot = getBotFromList(ind);
    	if (bot == null) return;
    	bot.disconnect();
    }//GEN-LAST:event_disconnectSelectedButton1ActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        if (stats == null) return;
        killsPanel14.removeAll();
        killsPanel14.add(StatsChartsFactory.getKillsInTimeByBot(stats));
        killsPanel14.revalidate();

        killsByTypejPanel14.removeAll();
        killsByTypejPanel14.add(StatsChartsFactory.getKillsInTimeByBotType(stats));
        killsByTypejPanel14.revalidate();

        deathsByTypejPanel14.removeAll();
        deathsByTypejPanel14.add(StatsChartsFactory.getDeathsInTimeByBotType(stats));
        deathsByTypejPanel14.revalidate();

        weaponsjPanel14.removeAll();
        weaponsjPanel14.add(StatsChartsFactory.getWeaponUseageByBotBarChart(stats));
        weaponsjPanel14.revalidate();

        killsePerDeathjPanel14.removeAll();
        killsePerDeathjPanel14.add(StatsChartsFactory.getKillsPerEachDeathByBotType(stats));
        killsePerDeathjPanel14.revalidate();

        whoKillsWhomjPanel14.removeAll();
        whoKillsWhomjPanel14.add(StatsChartsFactory.getWhoKillsWhomBarChart(stats));
        whoKillsWhomjPanel14.revalidate();

    }//GEN-LAST:event_refreshButtonActionPerformed

    private void nrOfSmartBotsTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrOfSmartBotsTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrOfSmartBotsTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (stats == null) return;
        JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
        fc.setApproveButtonText("Save");
        fc.setDialogTitle("Save current statistics");
        fc.showOpenDialog(this);
        System.out.println("Saving stats to file: "+fc.getSelectedFile());
        stats.saveToFile(fc.getSelectedFile().getPath());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
        fc.setApproveButtonText("Open");
        fc.setDialogTitle("Open statistics");
        fc.showOpenDialog(this);
        System.out.println("Reading stats from file: "+fc.getSelectedFile());
        stats = BotStatistic.readFromFile(fc.getSelectedFile().getPath());
        refreshButtonActionPerformed(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    	System.setProperty("QUAKE2", BotsConfig.quakePath);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mf = new MainFrame();
                mf.setVisible(true);
//                Dbg.toAppend = mf.getMessagesTextArea();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allEntsRadioButton1;
    private javax.swing.JTextArea botStateInfoTextArea1;
    private javax.swing.JButton connectDebugedButton;
    private javax.swing.JButton connectOthersButton;
    private javax.swing.JButton connectSmartBotsjButton1;
    private javax.swing.JList connectedBotsList1;
    private javax.swing.JPanel deathsByTypejPanel14;
    private javax.swing.JButton disconnectSelectedButton1;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JRadioButton edgeFailuresRadioButton;
    private javax.swing.JRadioButton enemyInfoRadioButton1;
    private javax.swing.JTextArea fullInfo;
    private javax.swing.JScrollPane fullInfoScrollPane3;
    private javax.swing.JButton goToButton;
    private javax.swing.ButtonGroup infoButtonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel killsByTypejPanel14;
    private javax.swing.JPanel killsPanel14;
    private javax.swing.JPanel killsePerDeathjPanel14;
    private javax.swing.JTextArea messages;
    private javax.swing.JScrollPane messagesScrollPane1;
    private javax.swing.JRadioButton navPlanRadioButton;
    private javax.swing.JTextField nrBotsField;
    private javax.swing.JTextField nrOfSmartBotsTextField2;
    private javax.swing.JPanel panelRunBots;
    private javax.swing.JToggleButton pauseAnotherBotsToggle;
    private javax.swing.JToggleButton pauseToggleButton;
    private javax.swing.JRadioButton pickupFailuresRadioButton1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JList reqList;
    private javax.swing.JScrollPane reqListScrollPane2;
    private javax.swing.JTextArea selectedBotInfoTextArea1;
    private javax.swing.JButton sendCommandToAnothersButton;
    private javax.swing.JButton sendCommandToDBGButton;
    private javax.swing.JButton stepButton1;
    private javax.swing.JTextField stepSizeTextField2;
    private javax.swing.JRadioButton visibleEntsRadioButton2;
    private javax.swing.JRadioButton visibleWaypointsRadioButton2;
    private javax.swing.JPanel weaponsjPanel14;
    private javax.swing.JPanel whoKillsWhomjPanel14;
    // End of variables declaration//GEN-END:variables
    
    private SmartBot dbgBot = null;

    private BotStatistic stats = null;
    
    private Vector<MapBotBase> bots = new Vector<MapBotBase>();
    
    private Vector<GameObject> requiredList = new Vector<GameObject>();
    
    private DebugStepJob stepJob = null;
    
    private MainFrameUpdater updater = null;
    
    public JTextArea getMessagesTextArea() {
    	return messages;
    }
    
    private void updateBotsList() {
    	int lastSelection = connectedBotsList1.getSelectedIndex();
  
    	Vector<MapBotBase> smToDelete = new Vector<MapBotBase>();
    	for (MapBotBase b :  bots) {
    		if ( ! b.isConnected()) smToDelete.add(b);
    	}
    	bots.removeAll(smToDelete);
    	
    	if ( dbgBot != null && ! dbgBot.isConnected()) dbgBot = null;
    	
    	DefaultListModel m = new DefaultListModel();
    	for (MapBotBase b :  bots) {
    		m.addElement(b);
    	}
    	if (dbgBot != null) m.addElement(dbgBot);
    	
    	connectedBotsList1.setModel(m);
    	connectedBotsList1.setSelectedIndex(lastSelection);
    	connectedBotsList1ValueChanged(null);
    }
    
    BotBase getBotFromList(int ind) {
    	if (ind < 0 || ind > bots.size() + 1) return null;
    	if (ind < bots.size()) {
    		return bots.elementAt(ind);
    	}
    	else if (ind == bots.size()) return dbgBot;
    	return null;
    }
    
    public void updateDisplayedInfo() {
    	if (dbgBot != null && dbgBot.getFrameNumber() > 1) {
    		if (visibleWaypointsRadioButton2.isSelected()) visibleWaypointsRadioButton2ActionPerformed(null);
        	else if (allEntsRadioButton1.isSelected()) allEntsRadioButton1ActionPerformed(null);
        	else if (visibleEntsRadioButton2.isSelected()) visibleEntsRadioButton2ActionPerformed(null);
        	else if (navPlanRadioButton.isSelected()) navPlanRadioButtonActionPerformed(null);
        	else if (pickupFailuresRadioButton1.isSelected()) pickupFailuresRadioButton1ActionPerformed(null);
        	else if (edgeFailuresRadioButton.isSelected()) edgeFailuresRadioButtonActionPerformed(null);
        	else if (enemyInfoRadioButton1.isSelected()) enemyInfoRadioButton1ActionPerformed(null);
    		reqListValueChanged(null);
    		botStateInfoTextArea1.setText(dbgBot.toDetailedString());
    	}
    	
    	updateBotsList();
    }
    
    private void setReqList(Vector<GameObject> vect) {
    	int lastSelection = reqList.getSelectedIndex();
    	 requiredList.clear();
         requiredList.addAll(vect);
         DefaultListModel m = new DefaultListModel();
         for (Object o : requiredList) {
      	   m.addElement(o);
         }
         reqList.setModel(m);
         reqList.setSelectedIndex(lastSelection);
         fullInfo.setText("");
         reqListValueChanged(null);
    }
    
    private void setUpdater() {
    	if (updater != null) return;
    	updater = new MainFrameUpdater(this);
    	Thread t = new Thread(updater);
    	t.start();
    }

}
